# Generated by Django 2.2.7 on 2019-11-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrierName', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('layover', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('departureDate', models.DateField()),
                ('departureTime', models.TimeField()),
                ('fareEconomy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fareBusiness', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fareFirst', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remainingSeatsEconomy', models.IntegerField()),
                ('remainingSeatsBusiness', models.IntegerField()),
                ('remainingSeatsFirst', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=36)),
                ('bookingType', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel')], max_length=6)),
                ('bookingDate', models.DateField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paymentDetails', models.CharField(max_length=16)),
                ('companyName', models.CharField(default='company', max_length=30)),
                ('location', models.CharField(default='location', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('brand', models.CharField(default='hotel', max_length=30)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=2)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentAmount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paymentType', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('cardNumber', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
