# Generated by Django 2.2.7 on 2019-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobabygo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='USA', max_length=30),
            preserve_default=False,
        ),
    ]
