# Generated by Django 2.2.7 on 2019-11-23 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobabygo', '0002_hotel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creditNum',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='debitNum',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='Devvrat', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='Raghav', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userPhone',
            field=models.CharField(default='+91 0909090909', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=35, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
