# Generated by Django 2.2.7 on 2019-11-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobabygo', '0003_auto_20191123_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creditNum',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='debitNum',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
